-- ==============================================================================
-- SAMSCO PORTFOLIO & CMS DATABASE SCHEMA (RUN IN SUPABASE SQL EDITOR)
-- ==============================================================================

-- 1. Create Skills Table
CREATE TABLE IF NOT EXISTS public.skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    level INTEGER NOT NULL CHECK (level >= 0 AND level <= 100),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Experience Table
CREATE TABLE IF NOT EXISTS public.experience (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year TEXT NOT NULL,
    title TEXT NOT NULL,
    subtitle TEXT NOT NULL,
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Site Settings Table
CREATE TABLE IF NOT EXISTS public.site_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    color TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create Testimonials Table
CREATE TABLE IF NOT EXISTS public.testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name TEXT NOT NULL,
    client_role TEXT NOT NULL,
    company TEXT,
    content TEXT NOT NULL,
    rating INTEGER DEFAULT 5,
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Create Works Table (with all enhanced columns)
CREATE TABLE IF NOT EXISTS public.works (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    cat TEXT,
    url TEXT NOT NULL,
    type TEXT DEFAULT 'image',
    "projectUrl" TEXT,
    client TEXT,
    year TEXT,
    role TEXT,
    desc TEXT,
    tags TEXT,
    problem TEXT,
    process TEXT,
    result TEXT,
    "demoUrl" TEXT,
    "thumbnailUrl" TEXT,
    "aspectRatio" TEXT DEFAULT '16:9',
    "focalPoint" TEXT DEFAULT 'center',
    status TEXT DEFAULT 'published',
    "scheduledAt" TIMESTAMPTZ,
    order_index INTEGER DEFAULT 0,
    views INTEGER DEFAULT 0,
    plays INTEGER DEFAULT 0,
    clicks INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Add columns if table already existed previously (Idempotent migrations)
ALTER TABLE public.categories ADD COLUMN IF NOT EXISTS color TEXT;

ALTER TABLE public.works ADD COLUMN IF NOT EXISTS "thumbnailUrl" TEXT;
ALTER TABLE public.works ADD COLUMN IF NOT EXISTS "aspectRatio" TEXT DEFAULT '16:9';
ALTER TABLE public.works ADD COLUMN IF NOT EXISTS "focalPoint" TEXT DEFAULT 'center';
ALTER TABLE public.works ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'published';
ALTER TABLE public.works ADD COLUMN IF NOT EXISTS "scheduledAt" TIMESTAMPTZ;
ALTER TABLE public.works ADD COLUMN IF NOT EXISTS order_index INTEGER DEFAULT 0;
ALTER TABLE public.works ADD COLUMN IF NOT EXISTS views INTEGER DEFAULT 0;
ALTER TABLE public.works ADD COLUMN IF NOT EXISTS plays INTEGER DEFAULT 0;
ALTER TABLE public.works ADD COLUMN IF NOT EXISTS clicks INTEGER DEFAULT 0;

-- 8. Create Inquiries Table for Contact Form submissions
CREATE TABLE IF NOT EXISTS public.inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'New',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Enable Row Level Security (RLS) on all tables
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.works ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;

-- 10. Drop old policies to avoid duplicate conflicts
DROP POLICY IF EXISTS "Allow public read on skills" ON public.skills;
DROP POLICY IF EXISTS "Allow authenticated changes on skills" ON public.skills;
DROP POLICY IF EXISTS "Allow public read on experience" ON public.experience;
DROP POLICY IF EXISTS "Allow authenticated changes on experience" ON public.experience;
DROP POLICY IF EXISTS "Allow public read on site_settings" ON public.site_settings;
DROP POLICY IF EXISTS "Allow authenticated changes on site_settings" ON public.site_settings;
DROP POLICY IF EXISTS "Allow public read on categories" ON public.categories;
DROP POLICY IF EXISTS "Allow authenticated changes on categories" ON public.categories;
DROP POLICY IF EXISTS "Allow public read on testimonials" ON public.testimonials;
DROP POLICY IF EXISTS "Allow authenticated changes on testimonials" ON public.testimonials;
DROP POLICY IF EXISTS "Allow public read on works" ON public.works;
DROP POLICY IF EXISTS "Allow authenticated changes on works" ON public.works;
DROP POLICY IF EXISTS "Allow public insert on inquiries" ON public.inquiries;
DROP POLICY IF EXISTS "Allow authenticated read/manage on inquiries" ON public.inquiries;

-- 11. Create Security Policies
CREATE POLICY "Allow public read on skills" ON public.skills FOR SELECT USING (true);
CREATE POLICY "Allow authenticated changes on skills" ON public.skills FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow public read on experience" ON public.experience FOR SELECT USING (true);
CREATE POLICY "Allow authenticated changes on experience" ON public.experience FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow public read on site_settings" ON public.site_settings FOR SELECT USING (true);
CREATE POLICY "Allow authenticated changes on site_settings" ON public.site_settings FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow public read on categories" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Allow authenticated changes on categories" ON public.categories FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow public read on testimonials" ON public.testimonials FOR SELECT USING (true);
CREATE POLICY "Allow authenticated changes on testimonials" ON public.testimonials FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow public read on works" ON public.works FOR SELECT USING (true);
CREATE POLICY "Allow authenticated changes on works" ON public.works FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow public insert on inquiries" ON public.inquiries FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated read/manage on inquiries" ON public.inquiries FOR ALL USING (auth.role() = 'authenticated');
